# 100 numpy exercises

#### 1. Import the numpy package under the name `np`

In [2]:
import numpy as np 

#### 2. Print the numpy version and the configuration 

In [12]:
np.version.version


'1.24.3'

#### 3. Create a null vector of size 10 

In [15]:
null_vector = np.zeros(10)
print(null_vector)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array

In [16]:
size = null_vector.nbytes
print(f'Memory size of our Null vector is:{size} bytes')

Memory size of our Null vector is:80 bytes


#### 5. How to get the documentation of the numpy add function from the command line?

In [ ]:
pydoc numpy.add 

#### 6. Create a null vector of size 10 but the fifth value which is 1

In [18]:
null_vector = np.zeros(10)
null_vector[4]=1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49

In [19]:
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last)

In [20]:
reversed_vector = vector[::-1]
print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [21]:
matrix = np.array([(0,1,2),(3,4,5),(6,7,8)])
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [25]:
a = np.array([1,2,0,0,4,0])
non_zeros = np.nonzero(a)
print(non_zeros)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix

In [26]:
identity_matrix =np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [31]:
array = np.random.rand(3,3,3)
print(array)

[[[0.57411265 0.22442017 0.32358392]
  [0.83618248 0.25922891 0.60486008]
  [0.67453375 0.6469919  0.90079363]]

 [[0.55975806 0.97512809 0.20972291]
  [0.33540471 0.70690595 0.50972617]
  [0.53826548 0.00742863 0.5911576 ]]

 [[0.39382651 0.32826827 0.34561165]
  [0.92412649 0.97370967 0.06428002]
  [0.09055879 0.89000461 0.27908015]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [41]:
array1 = np.random.rand(10,10)

minimum_value = np.min(array1)
maximum_value = np.max(array1)


print(array1)
print(f"The minimum value is: {minimum_value}")
print(f"The maximun Value is: {maximum_value}")

[[0.48623711 0.23742124 0.28644894 0.69354107 0.3936368  0.40922132
  0.65251067 0.74184373 0.04708973 0.59128928]
 [0.35178947 0.64862165 0.47029037 0.91232169 0.28762303 0.22860537
  0.38489086 0.50599819 0.62609445 0.24109205]
 [0.38575636 0.87117822 0.34751907 0.20709022 0.16800001 0.31374579
  0.73827585 0.89656551 0.96231545 0.38739463]
 [0.2284654  0.03420016 0.9913322  0.04763388 0.05665816 0.95516166
  0.11935556 0.81678386 0.55972893 0.05162663]
 [0.50994866 0.48511293 0.5968827  0.86147142 0.27639739 0.15340254
  0.84629395 0.74654298 0.88523298 0.64289895]
 [0.99994999 0.12883469 0.91153172 0.81135229 0.23507366 0.27732768
  0.81146923 0.44437024 0.28162711 0.86710755]
 [0.0176301  0.69831065 0.63486912 0.03099781 0.76604683 0.93256626
  0.03771248 0.80468921 0.60240609 0.46423164]
 [0.57010261 0.71089955 0.42963452 0.60419336 0.90806363 0.25638828
  0.32576169 0.14637018 0.63580935 0.17594486]
 [0.70605464 0.42547999 0.01981486 0.17469714 0.22612148 0.81251409
  0.05212764

#### 14. Create a random vector of size 30 and find the mean value

In [42]:
vector1 = np.random.rand(30)

mean_value = np.mean(vector1)

print("Vector")
print(vector1)
print("mean value:", mean_value)

Vector
[0.06806342 0.51459818 0.76528968 0.17121242 0.70428905 0.22761876
 0.49638693 0.72380276 0.07321723 0.36451739 0.9305132  0.44521678
 0.8183303  0.59099002 0.9309538  0.07233213 0.26176434 0.18133047
 0.76612488 0.14875437 0.55137345 0.26410412 0.00370673 0.69634687
 0.57821314 0.93506722 0.26446866 0.36141359 0.56017408 0.95647477]
mean value: 0.48088829114049925


#### 15. Create a 2d array with 1 on the border and 0 inside

In [52]:
array_2d = np.array([(1,1,1),(1,0,1),(1,1,1)])
print(array_2d)

[[1 1 1]
 [1 0 1]
 [1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [56]:
array_2d2 = np.copy(array_2d-1)

print(array_2d2)

[[ 0  0  0]
 [ 0 -1  0]
 [ 0  0  0]]


#### 17. What is the result of the following expression?


In [57]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
array3 = np.array([(0,0,0,0,0), (1,0,0,0,0), (1,2,0,0,0), (1,2,3,0,0), (1,2,3,4,0)])
print(array3)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [1 2 0 0 0]
 [1 2 3 0 0]
 [1 2 3 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [6]:
matrix2 = np.zeros([8,8], dtype=int)

matrix2[1::2, ::2] = 1 
matrix2[::2, 1::2] = 1
print(matrix2)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [13]:
multiarray = np.random.rand(6,7,8)

multiarray2 = multiarray.flatten()

index_100th = np.where(multiarray2 == multiarray2[99])

print(index_100th)

(array([99], dtype=int64),)


#### 21. Create a checkerboard 8x8 matrix using the tile function

In [4]:
tile = np.array([[0,1], [1,0]])

checkboard = np.tile(tile,(4,4))

print(checkboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix

In [5]:
matrix = np.random.rand(5,5)

min_val = np.min(matrix)
max_val = np.max(matrix)

normalized_matrix = (matrix - min_val) / (max_val- min_val)

print(normalized_matrix)

[[0.96209066 0.48697091 0.8548787  0.26817693 0.46467655]
 [0.87733911 0.95688114 0.59653445 0.06966059 0.        ]
 [0.5585907  0.61545037 0.67169984 0.09615715 0.77065854]
 [0.52107274 1.         0.53820094 0.35450513 0.87537154]
 [0.24124553 0.63032274 0.47025397 0.40761749 0.95201106]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [6]:
color_dtype = np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])

# Create an array of colors using the custom dtype
colors = np.array([(255, 0, 0, 255), (0, 255, 0, 255), (0, 0, 255, 255)], dtype=color_dtype)

# Access individual color components
red_values = colors['R']
green_values = colors['G']
blue_values = colors['B']
alpha_values = colors['A']

# Print the colors array and individual components
print(colors)
print(red_values)
print(green_values)
print(blue_values)
print(alpha_values)


[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)]
[255   0   0]
[  0 255   0]
[  0   0 255]
[255 255 255]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [13]:
matrix_5 = np.random.rand(5,3)

matrix_6 = np.random.rand(3,2)

print(np.dot(matrix_5, matrix_6))

[[1.39954453 0.90590574]
 [0.8587807  0.38230097]
 [1.33514982 0.6500737 ]
 [1.18620592 0.67944252]
 [0.91309823 0.30691238]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [26]:
marix_1d = np.array([1,2,3,4,5,6,7,8,9])

print(marix_1d)

negated = -1*marix_1d[3:8]
 
print(negated)

[1 2 3 4 5 6 7 8 9]
[-4 -5 -6 -7 -8]


#### 26. What is the output of the following script?

In [28]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal?

In [ ]:
Z**Z                # Correct expression
2 << Z >> 2         # Incorrect expression
Z <- Z              # Incorrect expression
1j*Z                # Incorrect expression
Z/1/1               # Correct expression
Z<Z>Z               # Correct expression

#### 28. What are the result of the following expressions?

In [29]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\user\AppData\Local\Temp\ipykernel_29328\548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
C:\Users\user\AppData\Local\Temp\ipykernel_29328\548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
C:\Users\user\AppData\Local\Temp\ipykernel_29328\548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ?

In [31]:
arr = np.array([1.2, 3.2, 6.4, 8.3, 8.9, 10.1, 5.5, 6.2])

round_arr = np.where(arr>=0, np.ceil(arr), np.floor(arr))

print(round_arr)

[ 2.  4.  7.  9.  9. 11.  6.  7.]


#### 30. How to find common values between two arrays?

In [32]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([5,6,7,8,9])

common_value = np.intersect1d( arr1, arr2)

print(common_value)

[5 6]


#### 31. How to ignore all numpy warnings (not recommended)?

In [36]:
import warnings
import numpy as np

# Ignore all NumPy warnings
warnings.filterwarnings("ignore", category=np.VisibleDeprecationWarning)
warnings.filterwarnings("ignore", category=np.RankWarning)



#### 32. Is the following expressions true?

In [37]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\user\AppData\Local\Temp\ipykernel_29328\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow?

In [1]:
import numpy as np
import datetime

# Get today's date
today = datetime.date.today()

# Calculate yesterday and tomorrow
yesterday = today - datetime.timedelta(days=1)
tomorrow = today + datetime.timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2024-02-04
Today: 2024-02-05
Tomorrow: 2024-02-06


#### 34. How to get all the dates corresponding to the month of July 2016?

In [2]:
import numpy as np
import datetime

# Define the start and end dates for July 2016
start_date = datetime.date(2016, 7, 1)
end_date = datetime.date(2016, 7, 31)

# Generate an array of dates
all_dates = np.arange(start_date, end_date + datetime.timedelta(days=1), dtype='datetime64')

print("All dates in July 2016:")
print(all_dates)

All dates in July 2016:
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [3]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# Perform the computation in place
result = np.multiply(np.add(A, B), np.divide(-A, 2))

print("Result:", result)

Result: [ -2.5  -7.  -13.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods

In [5]:
random_array = np.random.rand(5) * 10  # Adjust the size as needed

# Method 1: Using np.floor
method1 = np.floor(random_array)

# Method 2: Using np.trunc
method2 = np.trunc(random_array)

# Method 3: Using np.astype(int)
method3 = random_array.astype(int)

# Method 4: Using np.around
method4 = np.around(random_array).astype(int)

print("Original array:", random_array)
print("Method 1:", method1)
print("Method 2:", method2)
print("Method 3:", method3)
print("Method 4:", method4)


Original array: [3.33684042 4.79359523 9.43287583 1.24223099 8.16377776]
Method 1: [3. 4. 9. 1. 8.]
Method 2: [3. 4. 9. 1. 8.]
Method 3: [3 4 9 1 8]
Method 4: [3 5 9 1 8]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4

In [6]:
matrix = np.tile(np.arange(5), (5, 1))

print("Matrix:")
print(matrix)

Matrix:
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array

In [7]:
def my_generator():
    for i in range(10):
        yield i

# Create an array from the generator
array_from_generator = np.fromiter(my_generator(), dtype=int)

print("Array from generator:", array_from_generator)

Array from generator: [0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [8]:
vector = np.linspace(0, 1, 12)[1:-1]

print("Vector:")
print(vector)

Vector:
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it

In [9]:
random_vector = np.random.rand(10)

# Sort the vector
sorted_vector = np.sort(random_vector)

print("Random vector:", random_vector)
print("Sorted vector:", sorted_vector)

Random vector: [0.50030664 0.24966474 0.70860365 0.71289236 0.37184858 0.7278192
 0.50131197 0.95213854 0.52535837 0.43324062]
Sorted vector: [0.24966474 0.37184858 0.43324062 0.50030664 0.50131197 0.52535837
 0.70860365 0.71289236 0.7278192  0.95213854]


#### 41. How to sum a small array faster than np.sum?

In [10]:
small_array = np.array([1, 2, 3, 4, 5])

# Faster summation using np.add.reduce()
result = np.add.reduce(small_array)

print("Sum of small_array:", result)

Sum of small_array: 15


#### 42. Consider two random array A and B, check if they are equal

In [11]:
A = np.array([1, 2, 3])
B = np.array([1, 2, 3])

# Check if A and B are equal
are_equal = np.array_equal(A, B)

print("Are A and B equal?", are_equal)

Are A and B equal? True


#### 43. Make an array immutable (read-only)

In [12]:
my_array = np.array([1, 2, 3])

# Make the array read-only
my_array.flags.writeable = False

# Try to modify the array (will raise an error)
# my_array[0] = 10

print("Is the array read-only?", my_array.flags.writeable)

Is the array read-only? False


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [14]:
cartesian_matrix = np.random.rand(10, 2)

# Convert to polar coordinates
r = np.hypot(cartesian_matrix[:, 0], cartesian_matrix[:, 1])
theta = np.arctan2(cartesian_matrix[:, 1], cartesian_matrix[:, 0])

print("Polar coordinates (r, theta):")
print("r:", r)
print("theta:", theta)

Polar coordinates (r, theta):
r: [0.73689586 1.08170352 0.70230097 0.79415912 1.013793   0.50767164
 0.98302774 0.31860182 1.16001761 0.71190139]
theta: [0.6966672  0.58573033 1.52462895 1.30006705 0.56846286 0.71035902
 0.5854046  1.52609271 1.0045182  0.36835951]


#### 45. Create random vector of size 10 and replace the maximum value by 0

In [16]:
random_vector = np.random.rand(10)

# Find the index of the maximum value
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

print("Random vector with max replaced by 0:")
print(random_vector)

Random vector with max replaced by 0:
[0.20518918 0.         0.37712004 0.25147939 0.14294543 0.50811363
 0.94704057 0.3103697  0.90631952 0.7191082 ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area

In [17]:
x_coords, y_coords = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))

# Create a structured array
structured_array = np.empty((5, 5), dtype=[('x', float), ('y', float)])
structured_array['x'] = x_coords
structured_array['y'] = y_coords

print("Structured array:")
print(structured_array)

Structured array:
[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [18]:
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

# Construct the Cauchy matrix
C = 1 / (X[:, np.newaxis] - Y)

print("Cauchy matrix C:")
print(C)

Cauchy matrix C:
[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type

In [19]:
for dtype in [np.int8, np.int16, np.int32, np.int64]:
    info = np.iinfo(dtype)
    print(f"{dtype.__name__}: Min = {info.min}, Max = {info.max}")

# Floating-point types
for dtype in [np.float16, np.float32, np.float64]:
    info = np.finfo(dtype)
    print(f"{dtype.__name__}: Min = {info.min}, Max = {info.max}")

int8: Min = -128, Max = 127
int16: Min = -32768, Max = 32767
int32: Min = -2147483648, Max = 2147483647
int64: Min = -9223372036854775808, Max = 9223372036854775807
float16: Min = -65504.0, Max = 65504.0
float32: Min = -3.4028234663852886e+38, Max = 3.4028234663852886e+38
float64: Min = -1.7976931348623157e+308, Max = 1.7976931348623157e+308


#### 49. How to print all the values of an array?

In [20]:
my_array = np.array([1, 2, 3, 4, 5])

# Set print options to display all values
np.set_printoptions(threshold=np.inf)

print("All values of the array:")
print(my_array)

All values of the array:
[1 2 3 4 5]


#### 50. How to find the closest value (to a given scalar) in a vector?

In [21]:
vector = np.array([1.2, 3.4, 5.6, 7.8])

# Given scalar
scalar = 4.0

# Find the index of the closest value
closest_index = np.argmin(np.abs(vector - scalar))

# Get the closest value
closest_value = vector[closest_index]

print(f"Closest value to {scalar}: {closest_value}")

Closest value to 4.0: 3.4


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b)

In [22]:
dtype = np.dtype([('position', [('x', float), ('y', float)]),
                  ('color', [('r', int), ('g', int), ('b', int)])])

structured_array = np.zeros(1, dtype=dtype)

# Set values
structured_array['position']['x'] = 1.0
structured_array['position']['y'] = 2.0
structured_array['color']['r'] = 255
structured_array['color']['g'] = 128
structured_array['color']['b'] = 0

print("Structured array:")

Structured array:


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances

In [23]:
random_vector = np.random.rand(100, 2)

# Compute point-by-point distances
distances = np.linalg.norm(random_vector, axis=1)

print("Distances:")
print(distances)

Distances:
[0.90751034 0.6320804  0.4644356  0.82382322 0.97717954 1.30248935
 1.02135923 0.95981601 1.11184494 0.47182869 0.60180495 1.09324957
 0.88803541 0.53827509 1.00590529 0.33447795 0.51294325 0.119209
 0.91701878 1.29900765 0.94331158 0.15511236 0.4656932  0.75113832
 0.38645796 0.72827774 1.17235472 0.86276038 1.06380829 0.51382466
 0.75073811 0.40365662 0.64598625 0.6242715  0.48455773 0.47534065
 0.52087308 1.13052789 0.98781357 1.11754821 1.01105099 0.89049593
 1.1464428  0.95870638 0.719152   0.78376239 0.94737841 0.99667582
 0.87307459 0.49828082 0.36955086 1.0364481  0.31730622 0.937667
 0.88583419 0.53943526 0.89537844 1.11734037 0.56015928 0.28652328
 0.91865592 0.86055053 0.54675148 1.10707493 0.30839572 0.31917916
 0.4152265  0.3803421  0.99428267 0.68826596 0.81780274 0.93530267
 0.94415096 0.88952445 0.47007776 0.76166799 0.61662315 0.85884161
 0.9997366  0.77462819 1.12380212 0.79148968 1.21436036 0.57438773
 0.91888371 0.37505911 1.03172436 0.72529464 0.96931996

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [24]:
float_array = np.array([1.2, 2.3, 3.4], dtype=np.float32)

# Convert to integer array in place
float_array = float_array.astype(np.int32)

print("Integer array:")
print(float_array)

Integer array:
[1 2 3]


#### 54. How to read the following file?

In [27]:
ac = np.array([(1, 2, 3, 4, 5), (6,  ,  , 7, 8), (,  , 9,10,11)])

# Read the file (replace with the actual file path)
file_path = ac
data = np.genfromtxt(file_path, delimiter=',')

print("Data from the file:")
print(data)

SyntaxError: invalid syntax (4090680333.py, line 1)

#### 56. Generate a generic 2D Gaussian-like array

In [1]:

import numpy as np

# Define parameters
rows, cols = 5, 5
mean = 0
std_dev = 1

# Generate a 2D Gaussian-like array
gaussian_array = np.random.normal(mean, std_dev, size=(rows, cols))

print("Generated 2D Gaussian-like array:")
print(gaussian_array)


Generated 2D Gaussian-like array:
[[ 0.78950144  1.95828479 -0.04356521 -0.28272704 -0.96362589]
 [ 0.34561739 -0.07939218 -0.93508147  1.28200761 -1.29848083]
 [ 1.31415684 -0.14471416 -0.04367082 -0.28426271  0.45613503]
 [ 0.05720488  0.31038811 -1.50429124 -0.93184732  0.4073208 ]
 [ 0.24725666  0.55862137  1.12220358  1.12209846 -1.57644406]]


#### 57. How to randomly place p elements in a 2D array?

In [2]:
# Create an empty 2D array
arr = np.zeros((rows, cols))

# Randomly place 'p' elements
p = 5
random_indices = np.random.choice(rows * cols, p, replace=False)
arr.flat[random_indices] = 1

print("2D array with randomly placed elements:")
print(arr)


2D array with randomly placed elements:
[[0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 1. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix

In [3]:
# Create a sample matrix
matrix = np.random.rand(rows, cols)

# Subtract row means
row_means = np.mean(matrix, axis=1, keepdims=True)
centered_matrix = matrix - row_means

print("Matrix with row means subtracted:")
print(centered_matrix)


Matrix with row means subtracted:
[[ 0.41182006 -0.35730949  0.25107397 -0.32659456  0.02101001]
 [-0.0831618  -0.35726336  0.08047986  0.35829079  0.00165452]
 [ 0.35354358 -0.51384383  0.33503996 -0.03174903 -0.14299068]
 [-0.06929795 -0.15262112  0.49075797 -0.14780983 -0.12102906]
 [-0.31992665  0.29852575  0.26786085 -0.42490318  0.17844324]]


#### 59. How to sort an array by the nth column?

In [4]:
# Create a sample 2D array
array = np.random.randint(0, 10, size=(rows, cols))

# Sort by the 2nd column (index 1)
sorted_array = array[array[:, 1].argsort()]

print("Array sorted by the 2nd column:")
print(sorted_array)


Array sorted by the 2nd column:
[[7 0 9 9 5]
 [3 4 7 8 0]
 [0 5 5 9 1]
 [0 8 1 8 2]
 [5 8 4 1 8]]


#### 60. How to tell if a given 2D array has null columns?

In [5]:
# Check if any column has all zeros
has_null_columns = np.all(array == 0, axis=0)

print(f"Does the array have null columns? {has_null_columns.any()}")


Does the array have null columns? False


#### 61. Find the nearest value from a given value in an array

In [6]:
# Create an array
values = np.array([1, 5, 9, 12, 15])

# Given value
target_value = 8

# Find the index of the nearest value
nearest_index = np.abs(values - target_value).argmin()
nearest_value = values[nearest_index]

print(f"Nearest value to {target_value} is {nearest_value}")


Nearest value to 8 is 9


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

In [7]:
# Create two arrays
a = np.array([[1, 2, 3]])
b = np.array([[4], [5], [6]])

# Compute their sum using an iterator
result = np.sum(np.multiply(a, b))

print(f"Sum of the arrays: {result}")


Sum of the arrays: 90


#### 63. Create an array class that has a name attribute

In [8]:
class NamedArray(np.ndarray):
    def __new__(cls, input_array, name="Unnamed Array"):
        obj = np.asarray(input_array).view(cls)
        obj.name = name
        return obj

# Example usage
my_array = NamedArray([1, 2, 3], name="My Custom Array")
print(f"Array name: {my_array.name}")


Array name: My Custom Array


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [9]:

# Example vectors
V = np.array([10, 20, 30, 40, 50])
I = np.array([1, 3, 4])  # Indices to modify

# Add 1 to elements at specified indices
V[I] += 1

print("Modified vector V:")
print(V)


Modified vector V:
[10 21 30 41 51]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

In [ ]:
# Example vectors
X = np.array([5, 3, 8, 2, 6])
I = np.array([0, 2, 1, 3])  # Indices for accumulation

# Initialize an array F with zeros
F = np.zeros_like(X)

# Accumulate elements of X into F based on indices
np.add.at(F, I, X)

print("Accumulated array F:")
print(F)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

In [ ]:
# Example image (replace with your actual image data)
image = np.random.randint(0, 256, size=(w, h, 3), dtype=np.uint8)

# Reshape the image to a 2D array (w*h, 3)
reshaped_image = image.reshape(-1, 3)

# Compute unique colors
unique_colors = np.unique(reshaped_image, axis=0)

print(f"Number of unique colors: {len(unique_colors)}")

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once?

In [12]:
# Example 4D array (replace with your actual data)
arr_4d = np.random.rand(2, 3, 4, 5)

# Sum over the last two axes
result = np.sum(arr_4d, axis=(-2, -1))

print("Sum over the last two axes:")
print(result)


Sum over the last two axes:
[[ 8.67711469  9.58847392 11.05313548]
 [10.26415668 11.36028107 10.14454103]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices?

In [13]:
# Example vectors
D = np.array([10, 20, 30, 40, 50])
S = np.array([0, 1, 0, 1, 2])  # Subset indices (0, 1, 2)

# Compute means of subsets
unique_subset_indices = np.unique(S)
subset_means = [np.mean(D[S == i]) for i in unique_subset_indices]

print("Means of subsets:")
print(subset_means)


Means of subsets:
[20.0, 30.0, 50.0]


#### 69. How to get the diagonal of a dot product?

In [14]:
# Example matrices (replace with your actual data)
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)

# Compute dot product
dot_product = np.dot(A, B)

# Get the diagonal
diagonal = np.diag(dot_product)

print("Diagonal of the dot product:")
print(diagonal)


Diagonal of the dot product:
[0.74262931 1.22566204 0.51621733]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [15]:
original_vector = np.array([1, 2, 3, 4, 5])
new_vector = np.zeros(len(original_vector) + 3 * (len(original_vector) - 1))
new_vector[::4] = original_vector

print("New vector with interleaved")

New vector with interleaved


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

In [16]:
# Create arrays A and B (replace with your actual data)
A = np.random.rand(5, 5, 3)
B = np.random.rand(5, 5)

# Multiply element-wise
result = np.multiply(A, B[:, :, np.newaxis])

print("Result of element-wise multiplication:")
print(result)


Result of element-wise multiplication:
[[[0.04911217 0.08307803 0.12053088]
  [0.05938968 0.0537191  0.03168988]
  [0.24290943 0.05371797 0.51491313]
  [0.03522981 0.13631427 0.04776351]
  [0.53784604 0.36318296 0.36262186]]

 [[0.0345933  0.04922563 0.05596556]
  [0.00281657 0.00448007 0.00922221]
  [0.06458484 0.07548664 0.04070516]
  [0.84387504 0.53925067 0.84533337]
  [0.24816917 0.28791948 0.21119621]]

 [[0.6217039  0.04457098 0.07984036]
  [0.542619   0.43631272 0.35379573]
  [0.33628918 0.02970584 0.36221333]
  [0.0356095  0.01713554 0.01778351]
  [0.23366208 0.03314616 0.3216633 ]]

 [[0.26474144 0.23396724 0.30052388]
  [0.30673859 0.13763706 0.0128181 ]
  [0.38947087 0.14945394 0.02740595]
  [0.01644289 0.54495274 0.00739944]
  [0.19500574 0.58566196 0.45908826]]

 [[0.3081537  0.42637053 0.3437584 ]
  [0.00321337 0.00116827 0.01154012]
  [0.05882472 0.42775579 0.36901036]
  [0.51537333 0.00297889 0.11649113]
  [0.36821296 0.93436755 0.14443716]]]


#### 72. How to swap two rows of an array?

In [17]:
# Create a sample 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Swap rows 0 and 1
arr[0], arr[1] = arr[1], arr[0]

print("Array with swapped rows:")
print(arr)


Array with swapped rows:
[[4 5 6]
 [4 5 6]
 [7 8 9]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles 

In [18]:
# Example triplets (replace with your actual data)
triplets = np.array([[1, 2, 3],
                      [2, 3, 4],
                      [3, 4, 5],
                      # ... more triplets ...
                     ])

# Extract unique line segments
line_segments = np.unique(triplets[:, [0, 1, 1, 2]], axis=0)

print("Unique line segments:")
print(line_segments)


Unique line segments:
[[1 2 2 3]
 [2 3 3 4]
 [3 4 4 5]]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? 

In [19]:
# Example sorted array C (replace with your actual data)
C = np.array([2, 3, 1, 0, 4])

# Create array A with appropriate values
A = np.repeat(np.arange(len(C)), C)

print("Array A satisfying np.bincount(A) == C:")
print(A)


Array A satisfying np.bincount(A) == C:
[0 0 1 1 1 2 4 4 4 4]


#### 75. How to compute averages using a sliding window over an array?

In [20]:
# Example 1D array Z (replace with your actual data)
Z = np.array([10, 20, 30, 40, 50, 60])

# Define sliding window size (e.g., 3)
window_size = 3

# Compute moving averages
moving_averages = np.convolve(Z, np.ones(window_size) / window_size, mode='valid')

print(f"Moving averages with window size {window_size}:")
print(moving_averages)


Moving averages with window size 3:
[20. 30. 40. 50.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

In [ ]:
# Example 1D array Z (replace with your actual data)
Z = np.array([10, 20, 30, 40, 50])

# Build the 2D array
num_rows = len(Z)
shifted_rows = np.vstack([Z[i:] for i in range(num_rows)])

print("2D array with shifted rows:")
print(shifted_rows)

#### 77. How to negate a boolean, or to change the sign of a float inplace?

In [22]:
# Example boolean array and float array
bool_array = np.array([True, False, True])
float_array = np.array([1.0, -2.0, 3.0])

# Negate boolean array inplace
bool_array = np.logical_not(bool_array)

# Change sign of float array inplace
float_array *= -1

print("Negated boolean array:")
print(bool_array)
print("Float array")

Negated boolean array:
[False  True False]
Float array


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?

In [23]:
import numpy as np

def distance_to_line(p, P0, P1):
    # Compute vector from P0 to P1
    v = P1 - P0

    # Compute vector from P0 to p
    w = p - P0

    # Compute projection of w onto v
    proj = np.dot(w, v) / np.dot(v, v)

    # Compute closest point on the line
    closest_point = P0 + proj * v

    # Compute distance between p and closest_point
    distance = np.linalg.norm(p - closest_point)

    return distance

# Example points
p = np.array([3, 4])
P0 = np.array([[1, 2], [5, 6]])
P1 = np.array([[4, 3], [8, 7]])

distances = [distance_to_line(p, P0[i], P1[i]) for i in range(len(P0))]
print("Distances to each line:")
print(distances)


Distances to each line:
[1.264911064067352, 1.264911064067352]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?

In [24]:
# Example points
P = np.array([[2, 3], [4, 5], [6, 7]])
P0 = np.array([[1, 2], [5, 6]])
P1 = np.array([[4, 3], [8, 7]])

all_distances = []
for j in range(len(P)):
    distances = [distance_to_line(P[j], P0[i], P1[i]) for i in range(len(P0))]
    all_distances.append(distances)

print("Distances from each point to each line:")
print(np.array(all_distances))


Distances from each point to each line:
[[0.63245553 1.8973666 ]
 [1.8973666  0.63245553]
 [3.16227766 0.63245553]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary)

In [25]:
def extract_subpart(arr, center, shape, fill_value=0):
    half_shape = np.array(shape) // 2
    padded_arr = np.pad(arr, [(s, s) for s in half_shape], mode='constant', constant_values=fill_value)
    center_indices = np.array(center) + half_shape
    subpart = padded_arr[center_indices[0] - half_shape[0]:center_indices[0] + half_shape[0] + 1,
                         center_indices[1] - half_shape[1]:center_indices[1] + half_shape[1] + 1]
    return subpart

# Example array
arbitrary_array = np.random.randint(0, 10, size=(10, 10))

# Extract subpart centered at (5, 5) with shape (3, 3)
subpart = extract_subpart(arbitrary_array, center=(5, 5), shape=(3, 3))

print("Extracted subpart:")
print(subpart)


Extracted subpart:
[[2 5 3]
 [0 0 0]
 [8 5 2]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

In [ ]:
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
R = Z[:-3].reshape(-1, 4)

print("Array R:")
print(R)

#### 82. Compute a matrix rank

In [27]:
matrix = np.random.rand(4, 4)  # Replace with your actual matrix
rank = np.linalg.matrix_rank(matrix)

print(f"Matrix rank: {rank}")


Matrix rank: 4


#### 83. How to find the most frequent value in an array?

In [28]:
# Example array
arr = np.array([1, 2, 3, 1, 2, 1, 1, 1, 3, 2, 2, 1])

# Compute counts of each value
counts = np.bincount(arr)

# Find the most frequent value
most_frequent_value = np.argmax(counts)

print(f"Most frequent value: {most_frequent_value}")


Most frequent value: 1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix

In [29]:
# Create a random 10x10 matrix
matrix = np.random.randint(0, 100, size=(10, 10))

# Extract contiguous 3x3 blocks
blocks = [matrix[i:i+3, j:j+3] for i in range(8) for j in range(8)]

print("Contiguous 3x3 blocks:")
for block in blocks:
    print(block)


Contiguous 3x3 blocks:
[[54 96 43]
 [68 50 93]
 [ 9 52 38]]
[[96 43 37]
 [50 93 80]
 [52 38 59]]
[[43 37 32]
 [93 80 72]
 [38 59 42]]
[[37 32 10]
 [80 72 24]
 [59 42  2]]
[[32 10 16]
 [72 24 62]
 [42  2 61]]
[[10 16 76]
 [24 62 20]
 [ 2 61 71]]
[[16 76  1]
 [62 20 16]
 [61 71 38]]
[[76  1 62]
 [20 16  1]
 [71 38 94]]
[[68 50 93]
 [ 9 52 38]
 [36 52 50]]
[[50 93 80]
 [52 38 59]
 [52 50 41]]
[[93 80 72]
 [38 59 42]
 [50 41 58]]
[[80 72 24]
 [59 42  2]
 [41 58 34]]
[[72 24 62]
 [42  2 61]
 [58 34 73]]
[[24 62 20]
 [ 2 61 71]
 [34 73 42]]
[[62 20 16]
 [61 71 38]
 [73 42 54]]
[[20 16  1]
 [71 38 94]
 [42 54 69]]
[[ 9 52 38]
 [36 52 50]
 [34 74 48]]
[[52 38 59]
 [52 50 41]
 [74 48 82]]
[[38 59 42]
 [50 41 58]
 [48 82 29]]
[[59 42  2]
 [41 58 34]
 [82 29 43]]
[[42  2 61]
 [58 34 73]
 [29 43  2]]
[[ 2 61 71]
 [34 73 42]
 [43  2 63]]
[[61 71 38]
 [73 42 54]
 [ 2 63 93]]
[[71 38 94]
 [42 54 69]
 [63 93 44]]
[[36 52 50]
 [34 74 48]
 [ 1 93 58]]
[[52 50 41]
 [74 48 82]
 [93 58 19]]
[[50 41 58]
 [4

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i]

In [ ]:

class SymmetricArray(np.ndarray):
    def __new__(cls, input_array):
        obj = np.asarray(input_array).view(cls)
        return obj

    def __array_finalize__(self, obj):
        if obj is None:
            return
        # Ensure symmetry
        self[:] = (obj + obj.T) / 2

# Example usage
Z = SymmetricArray(np.random.rand(5, 5))
print(Z)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))

In [ ]:
# Example matrices and vectors (replace with your actual data)
p = 3
n = 4
matrices = np.random.rand(p, n, n)
vectors = np.random.rand(p, n, 1)

# Compute the sum of matrix products
result = np.sum(np.dot(matrices, vectors), axis=0)

print("Result shape:", result.shape)
print(result)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

In [ ]:
# Create a random 16x16 array
array_16x16 = np.random.randint(0, 100, size=(16, 16))

# Reshape into 4x4 blocks
blocks = array_16x16.reshape(4, 4, 4, 4)

# Compute the block-sum
block_sums = np.sum(blocks, axis=(2, 3))

print("Block-sums (4x4):")
print(block_sums)

#### 88. How to implement the Game of Life using numpy array

The Game of Life is a cellular automaton. You can represent the grid using a numpy array, update it based on the rules, and visualize the evolution. Implementing the entire Game of Life is beyond the scope of a single response, but you can start by creating the grid and defining the rules for cell evolution.

#### 89. How to get the n largest values of an array

In [ ]:
# Example array
arr = np.array([10, 5, 20, 15, 30, 25])

# Indices of sorted elements
sorted_indices = np.argsort(arr)

# Get the n largest values
n = 3
largest_values = arr[sorted_indices[-n:]]

print(f"{n} largest values:", largest_values)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)

In [4]:
import numpy as np

def cartesian_product(*arrays):
    broadcastable = np.ix_(*arrays)
    broadcasted = np.broadcast_arrays(*broadcastable)
    rows, cols = np.prod(broadcasted[0].shape), len(broadcasted)
    dtype = np.result_type(*arrays)
    out = np.empty(rows * cols, dtype=dtype)
    start, end = 0, rows
    for a in broadcasted:
        out[start:end] = a.reshape(-1)
        start, end = end, end + rows
    return out.reshape(cols, rows).T

# Example usage
alpha = np.array([0, 1])
beta = np.array([2, 3, 4])
result = cartesian_product(alpha, beta)

print("Cartesian product:")
print(result)


Cartesian product:
[[0 2]
 [0 3]
 [0 4]
 [1 2]
 [1 3]
 [1 4]]


#### 91. How to create a record array from a regular array?

In [5]:
regular_array = np.array([1, 2, 3])
field_names = ['value']

record_array = np.rec.fromarrays([regular_array], names=field_names)

print("Record array:")
print(record_array)


Record array:
[(1,) (2,) (3,)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods

In [6]:
Z = np.random.rand(1000000)  # Example large vector

# Method 1: Using numpy.power
result1 = np.power(Z, 3)

# Method 2: Using numpy.multiply
result2 = np.multiply(Z, np.multiply(Z, Z))

# Method 3: Using the ** operator
result3 = Z ** 3

# Verify that all methods produce the same result
print(np.allclose(result1, result2) and np.allclose(result1, result3))


True


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [2, 3, 1],
              [5, 6, 4]])

B = np.array([[1, 2],
              [3, 4]])

# Check if each row of B is contained in any row of A
mask = np.all(np.isin(B, A), axis=1)

# Get the rows of A that satisfy the condition
selected_rows = A[mask]

print("Rows of A containing elements of each row of B:")
print(selected_rows)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])

In [8]:
matrix = np.random.randint(0, 10, size=(10, 3))  # Example 10x3 matrix

# Find rows with unequal values
unique_rows, inverse_indices = np.unique(matrix, axis=0, return_inverse=True)
unequal_rows = unique_rows[np.bincount(inverse_indices) > 1]

print("Rows with unequal values:")
print(unequal_rows)


Rows with unequal values:
[]


#### 95. Convert a vector of ints into a matrix binary representation

In [ ]:
vector = np.array([5, 3, 7])  # Example vector of integers

# Convert to binary representation
binary_matrix = np.unpackbits(vector[:, np.newaxis], axis=1)

print("Binary matrix representation:")
print(binary_matrix)

#### 96. Given a two dimensional array, how to extract unique rows?

In [10]:
import numpy as np

# Example 2D array
original_array = np.array([[1, 1, 1, 0, 0, 0],
                           [0, 1, 1, 1, 0, 0],
                           [0, 1, 1, 1, 0, 0],
                           [1, 1, 1, 0, 0, 0],
                           [1, 1, 1, 1, 1, 0]])

# Get unique rows
unique_rows = np.unique(original_array, axis=0)

print("Unique rows:")
print(unique_rows)


Unique rows:
[[0 1 1 1 0 0]
 [1 1 1 0 0 0]
 [1 1 1 1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

In [ ]:
# Inner product (dot product):
np.einsum('i,i', A, B)


# Outer product
np.einsum('i,j->ij', A, B)


# Sum of elements
np.einsum('i', A)


# Element-wise multiplication:
np.einsum('i,i->i', A, B)


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples 

In [11]:
import numpy as np

# Example vectors X and Y
X = np.array([1, 2, 4, 6, 8])
Y = np.array([3, 5, 7, 9, 11])

# Number of equidistant samples
num_samples = 10

# Linearly interpolate between points
t = np.linspace(0, 1, num_samples)
sampled_X = np.interp(t, np.linspace(0, 1, len(X)), X)
sampled_Y = np.interp(t, np.linspace(0, 1, len(Y)), Y)

# Combine X and Y coordinates
sampled_path = np.column_stack((sampled_X, sampled_Y))

print("Sampled path:")
print(sampled_path)


Sampled path:
[[ 1.          3.        ]
 [ 1.44444444  3.88888889]
 [ 1.88888889  4.77777778]
 [ 2.66666667  5.66666667]
 [ 3.55555556  6.55555556]
 [ 4.44444444  7.44444444]
 [ 5.33333333  8.33333333]
 [ 6.22222222  9.22222222]
 [ 7.11111111 10.11111111]
 [ 8.         11.        ]]


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.

In [12]:
# Example 2D array X
X = np.array([[1, 2, 3],
              [0, 3, 2],
              [2, 1, 2],
              [3, 0, 1]])

n = 5  # Desired sum of multinomial draws

# Check if rows sum to n
valid_rows = np.sum(X, axis=1) == n

# Select valid rows
selected_rows = X[valid_rows]

print("Selected rows representing multinomial draws with sum", n)
print(selected_rows)


Selected rows representing multinomial draws with sum 5
[[0 3 2]
 [2 1 2]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).

In [13]:
# Example 1D array X (replace with your actual data)
X = np.random.normal(loc=10, scale=2, size=100)

# Number of bootstrap samples
N = 1000

# Resample with replacement
bootstrap_means = np.mean(np.random.choice(X, size=(N, len(X))), axis=1)

# Compute percentiles
lower_percentile = np.percentile(bootstrap_means, 2.5)
upper_percentile = np.percentile(bootstrap_means, 97.5)

print(f"Bootstrapped 95% confidence interval for the mean of X:")
print(f"Lower bound: {lower_percentile:.4f}")
print(f"Upper bound: {upper_percentile:.4f}")


Bootstrapped 95% confidence interval for the mean of X:
Lower bound: 9.5265
Upper bound: 10.2628
